### ISSUE TITLE
CFB Mode Support

### ISSUE THREAD

**Issue by zer0c0nf** [flakes/mirc_fish_10#40]
Hello,

is it possible to add to your next version of fish10 , the CFB mode support ?

Thanking you

zer0c0nf

**Comment by flakes** [comment]
Are there any other clients that support this?

**Comment by zer0c0nf** [comment]
This is the vision of improving safety and it probably will push customers to also improve security against attacks.

It is already very good to have a fish regularly updated , so if it can be even better it will be beneficial to everyone :)

**Comment by flakes** [comment]
CFB alone does not add any security at all. The weak link is authentication. I may or may not be working on a FiSH-based [OTR](https://en.wikipedia.org/wiki/Off-the-Record_Messaging) implementation that would expedite security levels to "NSA-proof if used correctly" - for queries. And since OTR is an established standard, it's also interoperable with other IRC clients. OTR is not currently available for group chats/channels (you may at least use the cbc: key prefix in FiSH 10), but people are working on making a that available as well.
