### ISSUE TITLE
curious

### ISSUE THREAD

**Issue by daslicht** [flakes/mirc_fish_10#56]
hi,
i am curious , wht not just use AES256 for excryption ? That should be more secure no ?
~dl

**Comment by flakes** [comment]
Even AES256 would not solve the underlying problems that

a) there is no protection against MITM, because there are no certificates or any means of "trust on first use"
b) secure encryption of group chats is a really hard problem.

I have been playing around with integrating LIBOTR into mIRC, but I doubt it would ever reach significant levels of usage.
